<?php

return [
    'numberOfContestants' => 4,
    'homeAdvantageFactor' => 10,
    'awayDisadvantageFactor' => 5,
    'minimalStrength' => 5,
    'maxGoalsForTeam' => 5,
    'teams' => [
        'AFC Bournemouth',
        'Arsenal',
        'Aston Villa',
        'Brighton & Hove Albion',
        'Burnley',
        'Chelsea',
        'Crystal Palace',
        'Everton',
        'Leicester City',
        'Liverpool',
        'Manchester City',
        'Manchester United',
        'Newcastle United',
        'Norwich City',
        'Sheffield United',
        'Southampton',
        'Tottenham Hotspur',
        'Watford',
        'West Ham United',
        'Wolverhampton Wanderers',
    ],
];
